name: Scrape Biwenger
on:
  schedule:
    - cron: '0 5 * * *'   # 07:00 hora España
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run scraper
        env:
          BIWENGER_EMAIL: ${{ secrets.BIWENGER_EMAIL }}
          BIWENGER_PASSWORD: ${{ secrets.BIWENGER_PASSWORD }}
          LIGA_ID: ${{ secrets.LIGA_ID }}
          PUBLIC_OUT_PATH: ./public/data.json
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: npm start

      - name: Upload public as artifact (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: public-output
          path: public

      - name: Deploy to gh-pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
